namespace SharpAlliance.Core.Screens
{
    public enum ScreenName
    {
        Unknown = 0,
        EDIT_SCREEN,
        SAVING_SCREEN,
        LOADING_SCREEN,
        ERROR_SCREEN,
        InitScreen,
        GAME_SCREEN,
        ANIEDIT_SCREEN,
        PALEDIT_SCREEN,
        DEBUG_SCREEN,
        MAP_SCREEN,
        LAPTOP_SCREEN,
        LOADSAVE_SCREEN,
        MAPUTILITY_SCREEN,
        FADE_SCREEN,
        MSG_BOX_SCREEN,
        MAINMENU_SCREEN,
        AUTORESOLVE_SCREEN,
        SAVE_LOAD_SCREEN,
        OPTIONS_SCREEN,
        SHOPKEEPER_SCREEN,
        SEX_SCREEN,
        GAME_INIT_OPTIONS_SCREEN,
        DEMO_EXIT_SCREEN,
        INTRO_SCREEN,
        CREDIT_SCREEN,
        AIVIEWER_SCREEN,
        QUEST_DEBUG_SCREEN,
        NullScreen,
        HelpScreen,
    }
}
