using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharpAlliance.Core.SubSystems.LaptopSubSystem;

public partial class Laptop
{
}
public enum LaptopText
{
    LAPTOP_BN_HLP_TXT_VIEW_EMAIL,
    LAPTOP_BN_HLP_TXT_BROWSE_VARIOUS_WEB_SITES,
    LAPTOP_BN_HLP_TXT_VIEW_FILES_AND_EMAIL_ATTACHMENTS,
    LAPTOP_BN_HLP_TXT_READ_LOG_OF_EVENTS,
    LAPTOP_BN_HLP_TXT_VIEW_TEAM_INFO,
    LAPTOP_BN_HLP_TXT_VIEW_FINANCIAL_SUMMARY_AND_HISTORY,
    LAPTOP_BN_HLP_TXT_CLOSE_LAPTOP,

    LAPTOP_BN_HLP_TXT_YOU_HAVE_NEW_MAIL,
    LAPTOP_BN_HLP_TXT_YOU_HAVE_NEW_FILE,


    BOOKMARK_TEXT_ASSOCIATION_OF_INTERNATION_MERCENARIES,
    BOOKMARK_TEXT_BOBBY_RAY_ONLINE_WEAPON_MAIL_ORDER,
    BOOKMARK_TEXT_INSTITUTE_OF_MERCENARY_PROFILING,
    BOOKMARK_TEXT_MORE_ECONOMIC_RECRUITING_CENTER,
    BOOKMARK_TEXT_MCGILLICUTTY_MORTUARY,
    BOOKMARK_TEXT_UNITED_FLORAL_SERVICE,
    BOOKMARK_TEXT_INSURANCE_BROKERS_FOR_AIM_CONTRACTS,

};
